# Generated by Django 5.0.7 on 2024-07-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('nif', models.CharField()),
                ('n_serie', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField()),
                ('fecha_baja', models.DateTimeField()),
                ('certificado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('nif', models.CharField()),
                ('public_key', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('n_serie', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('estado_solicitud', models.CharField(choices=[('en_proceso', 'En proceso'), ('aceptada', 'Aceptada')], default='en_proceso', max_length=50)),
            ],
        ),
    ]
