# Generated by Django 5.0.7 on 2024-07-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='certificate_name',
            field=models.CharField(max_length=255),
        ),
    ]
