# Generated by Django 5.0.7 on 2024-07-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_signeddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeypair',
            name='private_key_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userkeypair',
            name='public_key_url',
            field=models.CharField(max_length=500),
        ),
    ]
