# Generated by Django 5.0.7 on 2024-07-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userkeypair_private_key_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeypair',
            name='private_key_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userkeypair',
            name='public_key_url',
            field=models.TextField(),
        ),
    ]
